import Head from "next/head";
import React, { useState } from "react";
import styles from "../../styles/Home.module.css";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import SearchBanner from "../../components/SearchBanner";
import SearchSidebar from "../../components/SearchSidebar";
import BookCab from "../../components/BookCab";

export default function Home() {
  const [counter, setCounter] = useState(0);
  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };

  const [visible, setVisible] = useState(false);

  const toggleVisible = () => {
    const scrolled = document.documentElement.scrollTop;
    if (scrolled > 200) {
      setVisible(true);
    } else if (scrolled <= 200) {
      setVisible(false);
    }
  };

  React.useEffect(() => {
    const event = window.addEventListener("scroll", toggleVisible);

    return () => event;
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Yatri Cabs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className={styles.sectionBookCabHeader}>
          <Navbar />
          <SearchBanner />
        </div>
        <div className={styles.sectionBookCabBody}>
          <BookCab />
        </div>
        <Footer />
        <img
          src="/bx-up-arrow-alt.svg"
          onClick={scrollToTop}
          style={{
            zIndex: "100",
            position: "fixed",
            height: "40px",
            width: "40px",
            bottom: "5vh",
            right: "1.8rem",
            boderRadius: "10px",
            overflow: "hidden",
            backgroundColor: "rgb(255, 198, 0)",
            cursor: "pointer",
            display: visible ? "inline" : "none",
          }}
          className={styles.tapTop}
        />
      </div>
    </div>
  );
}
